---

- name: Install HAProxy
  yum:
    name: haproxy
    state: present
  notify: 
    - Start and enable HAProxy
    - Restart HAProxy

- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg }}"
  notify: 
    - Restart HAProxy



 