# ---
# - name: Install MySQL-python
#   yum:
#     name:
#       - python3-pip
#       - MySQL-python
#     state: present

# - name: Start and enable MySQL
#   service:
#    name: mariadb
#    state: started
#    enabled: yes

# - name: Install MySQL
#   yum:
#     name:
#       - mariadb
#       - mariadb-server
#     state: present
   

# - name: Create database
#   mysql_db:
#     name: "{{ db_name }}"
#     state: present
#   notify: Start and enable Mysql 

# - name: Create database user
#   mysql_user:
#     name: "{{ db_user }}"
#     password: "{{ db_password }}"
#     priv: "{{ db_name }}.*:ALL"
#     state: present
---
 
- name: Install MySQL
  yum:
    name:
      - mariadb
      - mariadb-server
    state: present
  notify: Start and enable MySQL
 
- name: Install MySQL-python
  yum:
    name:
      - python3-pip
      - MySQL-python
    state: present
 
- name: Start and enable MySQL
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
 
- name: Create database mariadb
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    priv: "{{ db_name }}"
  no_log: True  

 
